-- Add missing columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) DEFAULT 'blue';
ALTER TABLE users ADD COLUMN IF NOT EXISTS font_size VARCHAR(20) DEFAULT 'medium';
ALTER TABLE users ADD COLUMN IF NOT EXISTS issue_updates_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS community_activity_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS system_alerts_notifications BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_quality VARCHAR(20) DEFAULT 'high';
ALTER TABLE users ADD COLUMN IF NOT EXISTS video_quality VARCHAR(20) DEFAULT 'high';
ALTER TABLE users ADD COLUMN IF NOT EXISTS auto_upload BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cache_auto_clear BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS backup_sync BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location_services BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS data_collection BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS high_contrast BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS large_text BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS voice_over BOOLEAN DEFAULT FALSE;

-- Add missing AI verification columns to issues table
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_verification_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_confidence_score FLOAT DEFAULT 0.0;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS government_images TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS government_notes TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS citizen_verification_status VARCHAR(20);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS escalation_status VARCHAR(20) DEFAULT 'NONE';
ALTER TABLE issues ADD COLUMN IF NOT EXISTS escalation_date TIMESTAMP;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS resolution_date TIMESTAMP;
